# Generated by Django 6.0.6 on 2026-07-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='workspaces.workspace'),
        ),
    ]
