# Generated by Django 6.0.6 on 2026-07-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace'),
        ),
    ]
