# Generated by Django 6.0.6 on 2026-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_dedupe_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('milestone', 'Milestone'), ('risk', 'Risk'), ('deadline', 'Deadline'), ('invite', 'Invite'), ('comment', 'Comment'), ('mention', 'Mention')], max_length=20),
        ),
    ]
