# Generated by Django 6.0.6 on 2026-07-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_chats_and_chat_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('milestone', 'Milestone'), ('risk', 'Risk'), ('deadline', 'Deadline'), ('invite', 'Invite'), ('comment', 'Comment'), ('mention', 'Mention'), ('chat', 'Chat'), ('deal_task', 'Deal task')], max_length=20),
        ),
    ]
