# Generated by Django 6.0.6 on 2026-07-03 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_budget_projectbaseline_projectcharter_risk_and_more'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tracking.tracker'),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tracking.issuestatus'),
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wbs_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_nodes', to='tracking.tracker'),
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='workflow_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_nodes', to='tracking.issuestatus'),
        ),
    ]
