# Generated by Django 6.0.6 on 2026-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_ai_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsharelink',
            name='allow_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsharelink',
            name='chat_can_post',
            field=models.BooleanField(default=False),
        ),
    ]
