# Generated by Django 6.0.6 on 2026-07-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_p6a_crm_foundation'),
        ('projects', '0008_chat_ext_dm_threads_reactions_voice_guest_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_records', to='crm.person'),
        ),
    ]
