# Generated by Django 6.0.6 on 2026-08-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLessonsLearned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_went_well', models.TextField(blank=True)),
                ('what_went_wrong', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('knowledge_to_reuse', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_learned', to='projects.project')),
            ],
        ),
    ]
