# Generated by Django 6.0.6 on 2026-08-05 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_lessons_and_lane_roles'),
        ('projects', '0014_lessons_and_lane_roles'),
        ('tracking', '0003_alter_customfieldenumeration_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.CharField(choices=[('predictive', 'Predictive (Waterfall)'), ('scrum', 'Scrum'), ('hybrid', 'Hybrid')], default='predictive', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='schedule_locked',
            field=models.BooleanField(default=False, help_text='When True, scope/schedule edits require an approved change request.'),
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='gate_status',
            field=models.CharField(blank=True, choices=[('locked', 'Locked'), ('open', 'Open'), ('in_review', 'In Review'), ('passed', 'Passed'), ('failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='phase_key',
            field=models.CharField(blank=True, choices=[('requirements', 'Requirements'), ('design', 'Design'), ('implementation', 'Implementation'), ('verification', 'Verification'), ('maintenance', 'Maintenance')], help_text='Set on L1 Waterfall phase deliverables.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='phase_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='wbsnode',
            index=models.Index(fields=['project', 'phase_key'], name='projects_wb_project_788836_idx'),
        ),
        migrations.AddField(
            model_name='phasegate',
            name='baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_gates', to='projects.projectbaseline'),
        ),
        migrations.AddField(
            model_name='phasegate',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_phase_gates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phasegate',
            name='process_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_gates', to='process.processinstance'),
        ),
        migrations.AddField(
            model_name='phasegate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_gates', to='projects.project'),
        ),
        migrations.AddField(
            model_name='phasegate',
            name='wbs_phase_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_gates', to='projects.wbsnode'),
        ),
    ]
