# Generated by Django 6.0.6 on 2026-08-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_waterfall_methodology'),
        ('workspaces', '0009_obs_org_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbsnode',
            name='obs_role',
            field=models.ForeignKey(blank=True, help_text='OBS job role (not ACL role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_nodes', to='workspaces.obsrole'),
        ),
        migrations.AddField(
            model_name='wbsnode',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text='OBS department / org unit for this WBS node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_nodes', to='workspaces.orgunit'),
        ),
    ]
