# Generated by Django 6.0.6 on 2026-08-14 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_obs_org_breakdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WBSQualityCheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("evidence_url", models.URLField(blank=True, default="")),
                ("position", models.PositiveIntegerField(default=0)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wbs_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="projects.wbsnode",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
