# Generated by Django 6.0.6 on 2026-08-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_wbs_quality_checklist"),
        ("workspaces", "0009_obs_org_breakdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racientry",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raci_entries",
                to="projects.stakeholder",
            ),
        ),
        migrations.AddField(
            model_name="racientry",
            name="obs_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional OBS job role (instead of or with a named stakeholder).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raci_entries",
                to="workspaces.obsrole",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="racientry",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="racientry",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(stakeholder__isnull=False)
                    | models.Q(obs_role__isnull=False)
                ),
                name="raci_stakeholder_or_obs_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="racientry",
            constraint=models.UniqueConstraint(
                fields=("wbs_node", "stakeholder"),
                condition=models.Q(stakeholder__isnull=False),
                name="raci_unique_wbs_stakeholder",
            ),
        ),
        migrations.AddConstraint(
            model_name="racientry",
            constraint=models.UniqueConstraint(
                fields=("wbs_node", "obs_role"),
                condition=models.Q(
                    stakeholder__isnull=True, obs_role__isnull=False
                ),
                name="raci_unique_wbs_obs_role",
            ),
        ),
    ]
