# Generated by Django 6.0.6 on 2026-07-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_p6a_crm_foundation'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_ops_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_settings', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('business_outcome', models.TextField(blank=True, default='')),
                ('context', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('docs', 'Docs'), ('infra', 'Infra'), ('research', 'Research'), ('other', 'Other')], default='feature', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('review', 'Review'), ('qa', 'QA'), ('done', 'Done'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('assignee_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner')], default='', max_length=32)),
                ('ready_criterion', models.TextField(blank=True, default='')),
                ('done_criterion', models.TextField(blank=True, default='')),
                ('scope_in', models.TextField(blank=True, default='')),
                ('scope_out', models.TextField(blank=True, default='')),
                ('expected_checks', models.TextField(blank=True, default='')),
                ('result_artifact', models.TextField(blank=True, default='')),
                ('next_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner')], default='', max_length=32)),
                ('canon_url', models.URLField(blank=True, default='')),
                ('planning_doc_url', models.URLField(blank=True, default='')),
                ('acceptance_url', models.URLField(blank=True, default='')),
                ('external_pack_url', models.URLField(blank=True, default='')),
                ('github_repo', models.CharField(blank=True, default='', max_length=255)),
                ('github_branch', models.CharField(blank=True, default='', max_length=255)),
                ('github_commit', models.CharField(blank=True, default='', max_length=64)),
                ('github_pr_url', models.URLField(blank=True, default='')),
                ('github_pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('github_pr_state', models.CharField(blank=True, default='', max_length=32)),
                ('github_checks_url', models.URLField(blank=True, default='')),
                ('github_checks_status', models.CharField(blank=True, default='', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_delivery_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=16)),
                ('expected_artifact', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_subtasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='delivery.deliverytask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('goal', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('archived', 'Archived')], default='open', max_length=20)),
                ('planning_doc_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_delivery_epics', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_epics', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_epics', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='delivery.epic'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, default='')),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_sprints', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sprints', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='delivery.sprint'),
        ),
        migrations.CreateModel(
            name='TaskBlocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('needs_owner_decision', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_blockers', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_delivery_blockers', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='delivery.deliverytask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'Comment'), ('owner_request', 'Owner decision request')], default='comment', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='delivery.deliverytask')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner')], max_length=32)),
                ('to_role', models.CharField(choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner')], max_length=32)),
                ('done_summary', models.TextField()),
                ('left_summary', models.TextField(blank=True, default='')),
                ('branch_or_pr_url', models.URLField(blank=True, default='')),
                ('checks_url', models.URLField(blank=True, default='')),
                ('open_questions', models.TextField(blank=True, default='')),
                ('needs_owner_decision', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='delivery.deliverytask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.deliverytask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner')], max_length=32)),
                ('actor_type', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], default='human', max_length=16)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent_profiles', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent_profiles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['role', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_delivery_agent_profile_ws_user')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_idempotency_keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_idempotency_keys', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='delivery_de_created_fba5bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user', 'key'), name='uniq_delivery_idempotency_ws_user_key')],
            },
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['workspace', 'status'], name='delivery_de_workspa_353812_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['workspace', 'assignee_role', 'status'], name='delivery_de_workspa_a192bb_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['workspace', 'sprint', 'status'], name='delivery_de_workspa_f0dfe5_idx'),
        ),
    ]
