# Generated by Django 6.0.6 on 2026-07-27 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_agent_ops_p9'),
        ('projects', '0009_p6a_crm_foundation'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='allowed_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='allowed_projects',
            field=models.ManyToManyField(blank=True, related_name='delivery_agent_profiles', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='api_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_agent_profiles', to='workspaces.workspaceapitoken'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_service_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='architecture_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='github_review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taskblocker',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taskblocker',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskblocker',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_delivery_blockers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner'), ('reviewer', 'Reviewer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='assignee_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner'), ('reviewer', 'Reviewer')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='next_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner'), ('reviewer', 'Reviewer')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='kind',
            field=models.CharField(choices=[('comment', 'Comment'), ('owner_request', 'Owner decision request'), ('handoff_note', 'Handoff note'), ('blocker_note', 'Blocker note')], default='comment', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskhandoff',
            name='from_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner'), ('reviewer', 'Reviewer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='taskhandoff',
            name='to_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('documentation', 'Documentation Agent'), ('smart_contract', 'Smart Contract Agent'), ('backend', 'Backend Agent'), ('frontend', 'Frontend Agent'), ('qa', 'QA Agent'), ('human', 'Human Contributor'), ('observer', 'Observer'), ('planner', 'Planner'), ('reviewer', 'Reviewer')], max_length=32),
        ),
        migrations.CreateModel(
            name='AgentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='delivery.agentprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent_action_logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProjectMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True, default='')),
                ('docs_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_meta', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_project_meta', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_history', to='delivery.deliverytask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_access_logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='delivery_de_workspa_e62651_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='delivery.deliverytask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='delivery.deliverytask')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'depends_on'), name='uniq_delivery_task_dependency')],
            },
        ),
    ]
