# Generated by Django 6.0.6 on 2026-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_tz_e2e'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='github_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
