# Generated by Django 6.0.6 on 2026-07-28 11:51

import django.db.models.deletion
from django.db import migrations, models


def backfill_github_links(apps, schema_editor):
    DeliveryTask = apps.get_model("delivery", "DeliveryTask")
    TaskGitHubLink = apps.get_model("delivery", "TaskGitHubLink")
    for task in DeliveryTask.objects.all().iterator():
        if not (
            task.github_repo
            or task.github_branch
            or task.github_pr_number
            or task.github_pr_url
        ):
            continue
        if TaskGitHubLink.objects.filter(task_id=task.id).exists():
            continue
        TaskGitHubLink.objects.create(
            task_id=task.id,
            repo=task.github_repo or "",
            branch=task.github_branch or "",
            commit=task.github_commit or "",
            pr_number=task.github_pr_number,
            pr_url=task.github_pr_url or "",
            pr_state=task.github_pr_state or "",
            checks_url=task.github_checks_url or "",
            checks_status=task.github_checks_status or "",
            is_primary=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_ideal_tz_gaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGitHubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('commit', models.CharField(blank=True, default='', max_length=64)),
                ('pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, default='')),
                ('pr_state', models.CharField(blank=True, default='', max_length=32)),
                ('checks_url', models.URLField(blank=True, default='')),
                ('checks_status', models.CharField(blank=True, default='', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('attached_to_pr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_links', to='delivery.deliverytask')),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='taskgithubreview',
            name='github_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='delivery.taskgithublink'),
        ),
        migrations.AddIndex(
            model_name='taskgithublink',
            index=models.Index(fields=['repo', 'pr_number'], name='delivery_ta_repo_7975f4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskgithublink',
            index=models.Index(fields=['repo', 'branch'], name='delivery_ta_repo_f72442_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskgithublink',
            constraint=models.UniqueConstraint(condition=models.Q(('pr_number__isnull', False)), fields=('task', 'repo', 'pr_number'), name='uniq_delivery_task_github_pr'),
        ),
        migrations.RunPython(backfill_github_links, migrations.RunPython.noop),
    ]

