# Generated by Django 6.0.6 on 2026-07-19 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_p3_comments_capacity'),
        ('workspaces', '0003_p3_comments_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('work_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.wbsnode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
            },
        ),
    ]
