# Generated by Django 6.0.6 on 2026-08-04 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_process_work_node_and_deal_qualification'),
        ('projects', '0011_cross_project_dependencies'),
        ('timelog', '0001_initial'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='process_work_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='process.processworknode'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='wbs_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.wbsnode'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('process_work_node__isnull', True), ('wbs_node__isnull', False)), models.Q(('process_work_node__isnull', False), ('wbs_node__isnull', True)), _connector='OR'), name='timeentry_exactly_one_target'),
        ),
    ]
