# Generated by Django 6.0.6 on 2026-07-31 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_automation_crm_event_triggers'),
        ('process', '0002_usertask_wbs_binding'),
        ('projects', '0011_cross_project_dependencies'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent instance when this row tracks an embedded SubProcess.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='process.processinstance'),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='parent_spiff_task_id',
            field=models.CharField(blank=True, default='', help_text='Spiff SubWorkflowTask id on the parent workflow.', max_length=64),
        ),
        migrations.AddField(
            model_name='processinstance',
            name='subprocess_bpmn_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='processinstance',
            index=models.Index(fields=['parent', 'parent_spiff_task_id'], name='process_pro_parent__45f219_idx'),
        ),
    ]
