# Generated by Django 6.0.6 on 2026-08-04 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_subprocess_parent_link'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessWorkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpmn_id', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('node_type', models.CharField(choices=[('root', 'Root'), ('subprocess', 'SubProcess'), ('user_task', 'UserTask'), ('service_task', 'ServiceTask'), ('other', 'Other')], default='other', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('na', 'N/A')], default='open', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('raci_r', models.CharField(blank=True, default='', max_length=120)),
                ('raci_a', models.CharField(blank=True, default='', max_length=120)),
                ('raci_c', models.CharField(blank=True, default='', max_length=120)),
                ('raci_i', models.CharField(blank=True, default='', max_length=120)),
                ('predecessor_bpmn_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_work_nodes', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_nodes', to='process.processinstance')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='process.processworknode')),
                ('user_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_nodes', to='process.usertask')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_work_nodes', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['instance', 'parent'], name='process_pro_instanc_3041ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('instance', 'bpmn_id'), name='uniq_process_work_node_bpmn')],
            },
        ),
    ]
