# Generated by Django 6.0.6 on 2026-08-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_process_work_node_and_deal_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDefinitionLaneRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_id', models.CharField(max_length=120)),
                ('lane_name', models.CharField(blank=True, default='', max_length=255)),
                ('raci_type', models.CharField(choices=[('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], default='R', max_length=1)),
                ('role_key', models.CharField(blank=True, default='', help_text='Workspace role or crm_role slug (e.g. editor, sales)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_roles', to='process.processdefinition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lane_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lane_name', 'lane_id', 'raci_type'],
                'unique_together': {('definition', 'lane_id', 'raci_type')},
            },
        ),
    ]
