# Generated by Django 6.0.6 on 2026-07-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_webhookendpoint_webhookdelivery_workspaceapitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RUB', max_length=3),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('rate_to_base', models.DecimalField(decimal_places=8, help_text='How many base-currency units equal 1 unit of this currency.', max_digits=18)),
                ('as_of', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-as_of', '-id'],
                'unique_together': {('workspace', 'currency', 'as_of')},
            },
        ),
    ]
