# Generated by Django 6.0.6 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_p4_share_roles_fx'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='crm_role',
            field=models.CharField(blank=True, choices=[('', 'None'), ('sales_lead', 'Sales lead'), ('sales', 'Sales'), ('support', 'Support')], default='', max_length=20),
        ),
    ]
