# Generated by Django 6.0.6 on 2026-07-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_p6b_client_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ip_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
