# Generated by Django 6.0.6 on 2026-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_p7_security_2fa_sessions_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='crm_role',
            field=models.CharField(blank=True, choices=[('', 'None'), ('sales_lead', 'Sales lead'), ('sales', 'Sales'), ('support', 'Support'), ('accounting', 'Accounting'), ('marketing', 'Marketing')], default='', max_length=20),
        ),
    ]
