# Generated by Django 6.0.6 on 2026-08-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_crm_finance_deep_and_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs_roles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['position', 'name', 'id'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workspaces.orgunit')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['workspace', 'parent'], name='workspaces__workspa_5dea13_idx')],
            },
        ),
    ]
