# Generated by Django 6.0.6 on 2026-08-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_cardtransition'),
        ('process', '0004_process_work_node_and_deal_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='process_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='process.processinstance'),
        ),
        migrations.AddField(
            model_name='card',
            name='process_work_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='process.processworknode'),
        ),
    ]
