# Generated by Django 6.0.6 on 2026-07-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_format', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('list', 'List'), ('user', 'User')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('default_value', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(choices=[('project', 'Project'), ('issue', 'Issue')], default='issue', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_links', to='tracking.customfield')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_links', to='tracking.tracker')),
            ],
            options={
                'unique_together': {('custom_field', 'tracker')},
            },
        ),
        migrations.AddField(
            model_name='customfield',
            name='trackers',
            field=models.ManyToManyField(blank=True, related_name='custom_fields', through='tracking.CustomFieldTracker', to='tracking.tracker'),
        ),
        migrations.CreateModel(
            name='CustomFieldEnumeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerations', to='tracking.customfield')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('custom_field', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tracking.customfield')),
            ],
            options={
                'unique_together': {('custom_field', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_statuses', to='workspaces.workspace')),
            ],
            options={
                'verbose_name_plural': 'issue statuses',
                'ordering': ['position', 'id'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('workspace', 'name')},
        ),
    ]
