# Generated by Django 6.0.6 on 2026-07-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_seed_workspaces'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldenumeration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customfieldenumeration',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracking.customfieldenumeration'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_format',
            field=models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('percent', 'Percent'), ('bool', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('list', 'List'), ('link_list', 'Link list'), ('user', 'User'), ('url', 'URL'), ('email', 'Email')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldenumeration',
            unique_together={('custom_field', 'parent', 'name')},
        ),
    ]
