# Generated by Django 6.0.6 on 2026-07-22 16:16

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_p6a_crm_foundation'),
        ('projects', '0009_p6a_crm_foundation'),
        ('workspaces', '0006_p6b_client_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=crm.models.crm_file_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rule')], default='manual', max_length=20)),
                ('rule', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, default='#3b82f6', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_crm_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='social_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='person',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('note', 'Note'), ('invoice', 'Invoice'), ('order', 'Order'), ('other', 'Other')], default='note', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['workspace', 'occurred_at'], name='crm_activit_workspa_c3be98_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['person', 'occurred_at'], name='crm_activit_person__11590f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'occurred_at'], name='crm_activit_organiz_9d95f8_idx'),
        ),
        migrations.AddField(
            model_name='crmattachment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='crmattachment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.person'),
        ),
        migrations.AddField(
            model_name='crmattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crmattachment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_attachments', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='crmcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crmcomment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='crmcomment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.person'),
        ),
        migrations.AddField(
            model_name='crmcomment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_comments', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='organizationtag',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='persontag',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='crm.person'),
        ),
        migrations.AddField(
            model_name='segment',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='segments', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='segment',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='segments', to='crm.person'),
        ),
        migrations.AddField(
            model_name='segment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_segments', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tags', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='persontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='crm.tag'),
        ),
        migrations.AddField(
            model_name='organizationtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='crm.tag'),
        ),
        migrations.AddConstraint(
            model_name='crmattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('person__isnull', False)), models.Q(('organization__isnull', False), ('person__isnull', True)), _connector='OR'), name='crm_attachment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='crmcomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('person__isnull', False)), models.Q(('organization__isnull', False), ('person__isnull', True)), _connector='OR'), name='crm_comment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_crm_segment_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_crm_tag_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='persontag',
            constraint=models.UniqueConstraint(fields=('person', 'tag'), name='uniq_crm_person_tag'),
        ),
        migrations.AddConstraint(
            model_name='organizationtag',
            constraint=models.UniqueConstraint(fields=('organization', 'tag'), name='uniq_crm_org_tag'),
        ),
    ]
