# Generated by Django 6.0.6 on 2026-07-22 18:45

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_p6e_automations'),
        ('finance', '0002_p6c_deals'),
        ('projects', '0009_p6a_crm_foundation'),
        ('workspaces', '0006_p6b_client_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('imap', 'IMAP / Gmail IMAP'), ('telegram', 'Telegram bot')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CrmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('quote', 'Quote / КП'), ('invoice', 'Invoice'), ('contract', 'Contract')], max_length=20)),
                ('number', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('body', models.TextField(blank=True, default='')),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=crm.models.crm_document_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrmDocumentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrmSavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='channel',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('telegram', 'Telegram'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('telegram', 'Telegram'), ('note', 'Note'), ('invoice', 'Invoice'), ('order', 'Order'), ('other', 'Other')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('lead.created', 'Lead created'), ('lead.converted', 'Lead converted'), ('deal.created', 'Deal created'), ('deal.stage_changed', 'Deal stage changed'), ('schedule.daily', 'Daily schedule')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['workspace', 'channel', 'external_id'], name='crm_activit_workspa_14e366_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('workspace', 'channel', 'external_id'), name='uniq_crm_activity_external'),
        ),
        migrations.AddField(
            model_name='channelconnection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_channel_connections', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.person'),
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_documents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='crmdocument',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_documents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='crmdocumentpayment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.crmdocument'),
        ),
        migrations.AddField(
            model_name='crmdocumentpayment',
            name='finance_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_document_payments', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='crmsavedreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_saved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crmsavedreport',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_saved_reports', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['workspace', 'doc_type', 'status'], name='crm_crmdocu_workspa_3b1609_idx'),
        ),
        migrations.AddIndex(
            model_name='crmdocument',
            index=models.Index(fields=['workspace', 'due_date'], name='crm_crmdocu_workspa_a10d59_idx'),
        ),
    ]
