# Generated by Django 6.0.6 on 2026-07-24 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_p6ghi_omnichannel_commerce_analytics'),
        ('workspaces', '0007_p7_security_2fa_sessions_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('microsoft', 'Outlook / Microsoft 365'), ('google', 'Google Calendar')], max_length=20)),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_calendar_id', models.CharField(blank=True, default='', help_text='Outlook calendar id or Google calendar id (empty = primary)', max_length=255)),
                ('scopes', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.CharField(max_length=64)),
                ('external_event_id', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='crm.calendarconnection')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='calendarconnection',
            constraint=models.UniqueConstraint(fields=('workspace', 'user', 'provider'), name='uniq_calendar_connection_ws_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='calendareventlink',
            constraint=models.UniqueConstraint(fields=('connection', 'source_type', 'source_id'), name='uniq_calendar_event_link'),
        ),
    ]
