# Generated by Django 6.0.6 on 2026-07-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sync_deal_task_board_status(apps, schema_editor):
    DealTask = apps.get_model("crm", "DealTask")
    DealTask.objects.filter(is_done=True).update(board_status="done")


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_calendar_connection_sync"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dealtask",
            name="board_status",
            field=models.CharField(
                choices=[("todo", "To do"), ("doing", "Doing"), ("done", "Done")],
                default="todo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dealtask",
            name="checklist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dealtask",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dealtask",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.RunPython(sync_deal_task_board_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name="LeadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "board_status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("doing", "Doing"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=10,
                    ),
                ),
                ("checklist", models.JSONField(blank=True, default=list)),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("remind_before_days", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["is_done", "due_date", "id"],
            },
        ),
    ]
