# Generated by Django 6.0.6 on 2026-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_crm_tasks_ux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmdocument',
            name='doc_type',
            field=models.CharField(choices=[('quote', 'Quote / КП'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('bill', 'Vendor bill / AP')], max_length=20),
        ),
    ]
