# Generated by Django 6.0.6 on 2026-07-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_crm_finance_deep_and_roles'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='channel',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('stripe', 'Stripe'), ('onec', '1C'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('note', 'Note'), ('invoice', 'Invoice'), ('order', 'Order'), ('payment', 'Payment'), ('other', 'Other')], default='note', max_length=20),
        ),
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('onec', '1C'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('webhook_token', models.CharField(blank=True, default='', max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_integration_connectors', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['provider', 'name', 'id'],
                'indexes': [models.Index(fields=['workspace', 'provider', 'is_active'], name='crm_integra_workspa_9005c5_idx'), models.Index(fields=['webhook_token'], name='crm_integra_webhook_720f4a_idx')],
            },
        ),
    ]
