# Generated by Django 6.0.6 on 2026-07-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_crm_connectors_ondemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconnection',
            name='conflict_policy',
            field=models.CharField(choices=[('ours', 'Prefer Fast Plan (push wins)'), ('theirs', 'Prefer external calendar'), ('manual', 'Queue conflicts for manual resolve')], default='ours', max_length=10),
        ),
        migrations.AddField(
            model_name='calendareventlink',
            name='direction',
            field=models.CharField(blank=True, default='push', help_text='push | pull', max_length=10),
        ),
        migrations.AddField(
            model_name='calendareventlink',
            name='external_etag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='calendareventlink',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='channel',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('stripe', 'Stripe'), ('onec', '1C'), ('calendar', 'External calendar'), ('telephony', 'Telephony'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationconnector',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('onec', '1C'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('telephony', 'Telephony / PBX')], max_length=20),
        ),
        migrations.CreateModel(
            name='CalendarSyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(max_length=255)),
                ('local_title', models.CharField(blank=True, default='', max_length=255)),
                ('external_title', models.CharField(blank=True, default='', max_length=255)),
                ('local_start', models.DateTimeField(blank=True, null=True)),
                ('external_start', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_ours', 'Resolved: ours'), ('resolved_theirs', 'Resolved: theirs'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='crm.calendarconnection')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='crm.calendareventlink')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['connection', 'status'], name='crm_calenda_connect_d0173d_idx')],
            },
        ),
    ]
