# Generated by Django 6.0.6 on 2026-07-28 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_calendar_2way_and_telephony'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='channel',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('instagram', 'Instagram'), ('vk', 'VK'), ('stripe', 'Stripe'), ('onec', '1C'), ('calendar', 'External calendar'), ('telephony', 'Telephony'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('instagram', 'Instagram'), ('vk', 'VK'), ('note', 'Note'), ('invoice', 'Invoice'), ('order', 'Order'), ('payment', 'Payment'), ('other', 'Other')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='channelconnection',
            name='provider',
            field=models.CharField(choices=[('imap', 'IMAP / Gmail IMAP'), ('telegram', 'Telegram bot'), ('instagram', 'Instagram (webhook)'), ('vk', 'VK (callback)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='crmdocument',
            name='doc_type',
            field=models.CharField(choices=[('quote', 'Quote / КП'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('act', 'Completion act / Акт'), ('bill', 'Vendor bill / AP')], max_length=20),
        ),
        migrations.CreateModel(
            name='CrmSavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('clients', 'Clients'), ('deals', 'Deals'), ('leads', 'Leads')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_saved_filters', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_saved_filters', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['target', 'name', 'id'],
                'indexes': [models.Index(fields=['workspace', 'user', 'target'], name='crm_crmsave_workspa_8146e5_idx')],
            },
        ),
    ]
