# Generated by Django 6.0.6 on 2026-07-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_crm_polish_015'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('organization', 'Organization'), ('person', 'Person'), ('deal', 'Deal'), ('lead', 'Lead')], max_length=20)),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('date', 'Date'), ('select', 'Select'), ('multi_select', 'Multi select')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_custom_field_defs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['target', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CrmCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='crm.deal')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='crm.crmcustomfielddefinition')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='crm.lead')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='crm.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='crm.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='crmcustomfielddefinition',
            index=models.Index(fields=['workspace', 'target', 'is_active'], name='crm_crmcust_workspa_dffbaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmcustomfielddefinition',
            constraint=models.UniqueConstraint(fields=('workspace', 'target', 'key'), name='crm_cfield_ws_target_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='crmcustomfieldvalue',
            index=models.Index(fields=['definition'], name='crm_crmcust_definit_b93461_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmcustomfieldvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', False), ('person__isnull', True)), models.Q(('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', True), ('person__isnull', False)), models.Q(('deal__isnull', False), ('lead__isnull', True), ('organization__isnull', True), ('person__isnull', True)), models.Q(('deal__isnull', True), ('lead__isnull', False), ('organization__isnull', True), ('person__isnull', True)), _connector='OR'), name='crm_cfield_value_one_entity'),
        ),
    ]
