# Generated by Django 6.0.6 on 2026-07-29 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_custom_fields_016'),
        ('workspaces', '0008_crm_finance_deep_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crmdocument',
            name='stock_fulfilled',
            field=models.BooleanField(default=False, help_text='True after SKU qty deducted for paid invoice line_items.'),
        ),
        migrations.CreateModel(
            name='CrmSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='шт', max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_skus', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CrmStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('adjust', 'Manual adjust'), ('sale', 'Sale / invoice paid'), ('void_restore', 'Restore on void'), ('receive', 'Receive / restock')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='crm.crmdocument')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='crm.crmsku')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_stock_movements', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='crmsku',
            index=models.Index(fields=['workspace', 'is_active'], name='crm_crmsku_workspa_10e920_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmsku',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='crm_sku_ws_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='crmstockmovement',
            index=models.Index(fields=['workspace', 'sku', '-created_at'], name='crm_crmstoc_workspa_828372_idx'),
        ),
    ]
