# Generated by Django 6.0.6 on 2026-07-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_renewals_and_sku_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('lead.created', 'Lead created'), ('lead.converted', 'Lead converted'), ('deal.created', 'Deal created'), ('deal.stage_changed', 'Deal stage changed'), ('activity.created', 'Activity created'), ('document.accepted', 'Document accepted'), ('schedule.daily', 'Daily schedule')], max_length=40),
        ),
    ]
