# Generated by Django 6.0.6 on 2026-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_automation_crm_event_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='bant_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='bant_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='bant_need',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='bant_timeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='playbook_done',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='qualification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='playbook_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
