from django.urls import path

from crm import ai_views, automation_views, commerce_views, deals_views, leads_views, views

urlpatterns = [
    path("crm/organizations/", views.OrganizationListCreateView.as_view(), name="crm-orgs"),
    path(
        "crm/organizations/<int:org_id>/",
        views.OrganizationDetailView.as_view(),
        name="crm-org-detail",
    ),
    path(
        "crm/organizations/<int:org_id>/tags/",
        views.OrganizationTagView.as_view(),
        name="crm-org-tags",
    ),
    path(
        "crm/organizations/<int:org_id>/tags/<int:tag_id>/",
        views.OrganizationTagView.as_view(),
        name="crm-org-tag-detail",
    ),
    path("crm/people/", views.PersonListCreateView.as_view(), name="crm-people"),
    path(
        "crm/people/<int:person_id>/",
        views.PersonDetailView.as_view(),
        name="crm-person-detail",
    ),
    path(
        "crm/people/<int:person_id>/tags/",
        views.PersonTagView.as_view(),
        name="crm-person-tags",
    ),
    path(
        "crm/people/<int:person_id>/tags/<int:tag_id>/",
        views.PersonTagView.as_view(),
        name="crm-person-tag-detail",
    ),
    path("crm/activities/", views.ActivityListCreateView.as_view(), name="crm-activities"),
    path(
        "crm/activities/<int:activity_id>/",
        views.ActivityDetailView.as_view(),
        name="crm-activity-detail",
    ),
    path("crm/tags/", views.TagListCreateView.as_view(), name="crm-tags"),
    path(
        "crm/tags/<int:tag_id>/",
        views.TagDetailView.as_view(),
        name="crm-tag-detail",
    ),
    path("crm/segments/", views.SegmentListCreateView.as_view(), name="crm-segments"),
    path(
        "crm/segments/<int:segment_id>/",
        views.SegmentDetailView.as_view(),
        name="crm-segment-detail",
    ),
    path(
        "crm/segments/<int:segment_id>/members/",
        views.SegmentMembersView.as_view(),
        name="crm-segment-members",
    ),
    path("crm/comments/", views.CommentListCreateView.as_view(), name="crm-comments"),
    path(
        "crm/comments/<int:comment_id>/",
        views.CommentDetailView.as_view(),
        name="crm-comment-detail",
    ),
    path(
        "crm/attachments/",
        views.AttachmentListCreateView.as_view(),
        name="crm-attachments",
    ),
    path(
        "crm/attachments/<int:attachment_id>/",
        views.AttachmentDetailView.as_view(),
        name="crm-attachment-detail",
    ),
    path(
        "crm/projects/<int:project_id>/people/",
        views.ProjectPeopleView.as_view(),
        name="crm-project-people",
    ),
    path("crm/import-legacy/", views.CrmImportLegacyView.as_view(), name="crm-import-legacy"),
    path("crm/pipeline/", deals_views.PipelineBoardView.as_view(), name="crm-pipeline"),
    path("crm/deals/", deals_views.DealListCreateView.as_view(), name="crm-deals"),
    path(
        "crm/deals/forecast/",
        deals_views.DealForecastView.as_view(),
        name="crm-deals-forecast",
    ),
    path(
        "crm/deals/<int:deal_id>/",
        deals_views.DealDetailView.as_view(),
        name="crm-deal-detail",
    ),
    path(
        "crm/deals/<int:deal_id>/move/",
        deals_views.DealMoveView.as_view(),
        name="crm-deal-move",
    ),
    path(
        "crm/deals/<int:deal_id>/tasks/",
        deals_views.DealTaskListCreateView.as_view(),
        name="crm-deal-tasks",
    ),
    path(
        "crm/deals/<int:deal_id>/tasks/<int:task_id>/",
        deals_views.DealTaskDetailView.as_view(),
        name="crm-deal-task-detail",
    ),
    path("crm/leads/", leads_views.LeadListCreateView.as_view(), name="crm-leads"),
    path(
        "crm/leads/import/",
        leads_views.LeadImportView.as_view(),
        name="crm-leads-import",
    ),
    path(
        "crm/leads/<int:lead_id>/",
        leads_views.LeadDetailView.as_view(),
        name="crm-lead-detail",
    ),
    path(
        "crm/leads/<int:lead_id>/assign/",
        leads_views.LeadAssignView.as_view(),
        name="crm-lead-assign",
    ),
    path(
        "crm/leads/<int:lead_id>/convert/",
        leads_views.LeadConvertView.as_view(),
        name="crm-lead-convert",
    ),
    path(
        "crm/automations/",
        automation_views.AutomationListCreateView.as_view(),
        name="crm-automations",
    ),
    path(
        "crm/automations/templates/",
        automation_views.AutomationTemplateListView.as_view(),
        name="crm-automation-templates",
    ),
    path(
        "crm/automations/templates/apply/",
        automation_views.AutomationTemplateApplyView.as_view(),
        name="crm-automation-templates-apply",
    ),
    path(
        "crm/automations/runs/",
        automation_views.AutomationRunListView.as_view(),
        name="crm-automation-runs",
    ),
    path(
        "crm/automations/test/",
        automation_views.AutomationTestView.as_view(),
        name="crm-automation-test",
    ),
    path(
        "crm/automations/<int:rule_id>/",
        automation_views.AutomationDetailView.as_view(),
        name="crm-automation-detail",
    ),
    path("crm/ai/insights/", ai_views.CrmAiInsightsView.as_view(), name="crm-ai-insights"),
    path(
        "crm/ai/draft-email/",
        ai_views.CrmAiDraftEmailView.as_view(),
        name="crm-ai-draft-email",
    ),
    path("crm/ai/draft-kp/", ai_views.CrmAiDraftKpView.as_view(), name="crm-ai-draft-kp"),
    path(
        "crm/ai/activity-summary/",
        ai_views.CrmAiActivitySummaryView.as_view(),
        name="crm-ai-activity-summary",
    ),
    path(
        "crm/ai/suggest-tasks/",
        ai_views.CrmAiSuggestTasksView.as_view(),
        name="crm-ai-suggest-tasks",
    ),
    path(
        "crm/channels/",
        commerce_views.ChannelConnectionListCreateView.as_view(),
        name="crm-channels",
    ),
    path(
        "crm/channels/<int:connection_id>/",
        commerce_views.ChannelConnectionDetailView.as_view(),
        name="crm-channel-detail",
    ),
    path(
        "crm/channels/<int:connection_id>/sync/",
        commerce_views.ChannelConnectionSyncView.as_view(),
        name="crm-channel-sync",
    ),
    path(
        "crm/channels/telegram/<str:secret>/",
        commerce_views.TelegramWebhookView.as_view(),
        name="crm-telegram-webhook",
    ),
    path(
        "crm/documents/",
        commerce_views.CrmDocumentListCreateView.as_view(),
        name="crm-documents",
    ),
    path(
        "crm/documents/<int:document_id>/",
        commerce_views.CrmDocumentDetailView.as_view(),
        name="crm-document-detail",
    ),
    path(
        "crm/documents/<int:document_id>/pdf/",
        commerce_views.CrmDocumentPdfView.as_view(),
        name="crm-document-pdf",
    ),
    path(
        "crm/documents/<int:document_id>/payments/",
        commerce_views.CrmDocumentPaymentListCreateView.as_view(),
        name="crm-document-payments",
    ),
    path("crm/ar-ap/", commerce_views.CrmArApView.as_view(), name="crm-ar-ap"),
    path(
        "crm/analytics/",
        commerce_views.CrmAnalyticsView.as_view(),
        name="crm-analytics",
    ),
    path(
        "crm/saved-reports/",
        commerce_views.CrmSavedReportListCreateView.as_view(),
        name="crm-saved-reports",
    ),
    path(
        "crm/saved-reports/<int:report_id>/",
        commerce_views.CrmSavedReportDetailView.as_view(),
        name="crm-saved-report-detail",
    ),
]
