# Generated by Django 6.0.6 on 2026-06-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_budget_projectbaseline_projectcharter_risk_and_more'),
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
