# Generated by Django 6.0.6 on 2026-07-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_p6c_deals'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='CRM counterparty (prep for P6c+)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='crm.organization'),
        ),
    ]
