# Generated by Django 6.0.6 on 2026-07-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_chats_and_chat_notification_type'),
        ('projects', '0008_chat_ext_dm_threads_reactions_voice_guest_archive'),
        ('workspaces', '0005_p4_share_roles_fx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='chatroom_scope_target_xor',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chats.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, upload_to='chat_voice/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='dm_user_high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_rooms_as_high', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='dm_user_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_rooms_as_low', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='scope',
            field=models.CharField(choices=[('project', 'Project'), ('workspace', 'Workspace'), ('dm', 'Direct message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('disabled', 'Disabled'), ('announcements', 'Announcements only'), ('archived', 'Archived')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dm_user_high__isnull', True), ('dm_user_low__isnull', True), ('project__isnull', False), ('scope', 'project'), ('workspace__isnull', True)), models.Q(('dm_user_high__isnull', True), ('dm_user_low__isnull', True), ('project__isnull', True), ('scope', 'workspace'), ('workspace__isnull', False)), models.Q(('dm_user_high__isnull', False), ('dm_user_low__isnull', False), ('project__isnull', True), ('scope', 'dm'), ('workspace__isnull', False)), _connector='OR'), name='chatroom_scope_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'workspace')), fields=('workspace',), name='uniq_chatroom_workspace_scope'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'dm')), fields=('workspace', 'dm_user_low', 'dm_user_high'), name='uniq_chatroom_dm_pair'),
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chats.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatreaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='uniq_chat_reaction_user_emoji'),
        ),
    ]
