/** Compact 256-word list for 12-word recovery phrases (~96 bits). */
export const RECOVERY_WORDS = [
  "able", "acid", "acne", "acre", "aged", "aide", "aims", "airy",
  "ajar", "alarm", "album", "alert", "alien", "alike", "alive", "alloy",
  "alpha", "amber", "amigo", "ample", "anchor", "angel", "angle", "ankle",
  "apple", "apron", "aqua", "arbor", "arena", "argon", "armor", "arrow",
  "artist", "ashen", "aside", "asset", "atlas", "atom", "audio", "audit",
  "autumn", "avalon", "avenue", "avid", "avoid", "awake", "award", "aware",
  "axiom", "azure", "badge", "bagel", "baker", "balmy", "bamboo", "banjo",
  "barge", "basin", "batch", "beach", "beacon", "beard", "beast", "beaver",
  "beetle", "begin", "beige", "belly", "bench", "berry", "bible", "bike",
  "bingo", "birch", "bird", "blade", "blame", "blank", "blast", "blaze",
  "bleak", "blend", "bless", "blimp", "blind", "blink", "bliss", "blitz",
  "bloat", "block", "bloom", "blown", "blue", "bluff", "blunt", "blush",
  "board", "boast", "boat", "bobby", "bogus", "boil", "bold", "bolt",
  "bomb", "bond", "bone", "bonus", "boost", "booth", "boots", "borax",
  "born", "boss", "both", "bottle", "bottom", "bounce", "bound", "bowel",
  "bowl", "boxer", "brace", "brain", "brand", "brass", "brave", "bread",
  "break", "breed", "breeze", "brick", "bride", "brief", "bright", "bring",
  "brisk", "broad", "broil", "broke", "bronze", "broom", "brown", "brush",
  "buck", "buddy", "budget", "buff", "buggy", "build", "bulb", "bulge",
  "bulk", "bully", "bunch", "bunny", "burn", "burst", "bushel", "cabin",
  "cable", "cacao", "cache", "cactus", "cadet", "cafe", "cage", "cake",
  "calm", "camel", "camera", "camp", "canal", "candy", "canoe", "canvas",
  "canyon", "capable", "capital", "captain", "carbon", "card", "cargo", "carol",
  "carpet", "carry", "cart", "case", "cash", "casino", "cast", "casual",
  "catalog", "catch", "cattle", "caught", "cause", "caution", "cave", "ceiling",
  "celery", "cement", "census", "century", "cereal", "certain", "chair", "chalk",
  "champion", "change", "chaos", "chapter", "charge", "chase", "chat", "cheap",
  "check", "cheese", "chef", "cherry", "chest", "chicken", "chief", "child",
  "chimney", "choice", "choose", "chronic", "chuckle", "chunk", "churn", "cigar",
  "cinnamon", "circle", "citizen", "city", "civil", "claim", "clap", "clarify",
  "claw", "clay", "clean", "clerk", "clever", "click", "client", "cliff",
  "climb", "clinic", "clip", "clock", "clog", "close", "cloth", "cloud",
] as const;
