from django.urls import path

from accounts.security_views import WorkspaceIpAllowlistView
from workspaces.fx_views import (
    ExchangeRateDetailView,
    ExchangeRateListCreateView,
    WorkspaceFxConvertView,
    WorkspaceSettingsView,
)
from workspaces.views import (
    WorkspaceActivateView,
    WorkspaceAPITokenDetailView,
    WorkspaceAPITokenListCreateView,
    WorkspaceCapacityView,
    WorkspaceDashboardView,
    WorkspaceEventsView,
    WorkspaceInvitationAcceptView,
    WorkspaceInvitationDetailView,
    WorkspaceInvitationListCreateView,
    WorkspaceListView,
    WorkspaceMemberDetailView,
    WorkspaceMemberListView,
    WorkspaceMyTasksView,
    WorkspaceSearchView,
    WorkspaceWebhookDeliveryListView,
    WorkspaceWebhookDetailView,
    WorkspaceWebhookListCreateView,
    WorkspaceWebhookTestView,
)

urlpatterns = [
    path("workspaces/", WorkspaceListView.as_view(), name="workspace-list"),
    path(
        "workspaces/<int:workspace_id>/activate/",
        WorkspaceActivateView.as_view(),
        name="workspace-activate",
    ),
    path(
        "workspace/dashboard/",
        WorkspaceDashboardView.as_view(),
        name="workspace-dashboard",
    ),
    path(
        "workspace/search/",
        WorkspaceSearchView.as_view(),
        name="workspace-search",
    ),
    path(
        "workspace/events/",
        WorkspaceEventsView.as_view(),
        name="workspace-events",
    ),
    path(
        "workspace/my-tasks/",
        WorkspaceMyTasksView.as_view(),
        name="workspace-my-tasks",
    ),
    path(
        "workspace/capacity/",
        WorkspaceCapacityView.as_view(),
        name="workspace-capacity",
    ),
    path(
        "workspace/api-tokens/",
        WorkspaceAPITokenListCreateView.as_view(),
        name="workspace-api-tokens",
    ),
    path(
        "workspace/api-tokens/<int:token_id>/",
        WorkspaceAPITokenDetailView.as_view(),
        name="workspace-api-token-detail",
    ),
    path(
        "workspace/webhooks/",
        WorkspaceWebhookListCreateView.as_view(),
        name="workspace-webhooks",
    ),
    path(
        "workspace/webhooks/<int:endpoint_id>/",
        WorkspaceWebhookDetailView.as_view(),
        name="workspace-webhook-detail",
    ),
    path(
        "workspace/webhooks/<int:endpoint_id>/deliveries/",
        WorkspaceWebhookDeliveryListView.as_view(),
        name="workspace-webhook-deliveries",
    ),
    path(
        "workspace/webhooks/<int:endpoint_id>/test/",
        WorkspaceWebhookTestView.as_view(),
        name="workspace-webhook-test",
    ),
    path(
        "workspace/settings/",
        WorkspaceSettingsView.as_view(),
        name="workspace-settings",
    ),
    path(
        "workspace/ip-allowlist/",
        WorkspaceIpAllowlistView.as_view(),
        name="workspace-ip-allowlist",
    ),
    path(
        "workspace/exchange-rates/",
        ExchangeRateListCreateView.as_view(),
        name="workspace-exchange-rates",
    ),
    path(
        "workspace/exchange-rates/<int:rate_id>/",
        ExchangeRateDetailView.as_view(),
        name="workspace-exchange-rate-detail",
    ),
    path(
        "workspace/fx/convert/",
        WorkspaceFxConvertView.as_view(),
        name="workspace-fx-convert",
    ),
    path("workspace/members/", WorkspaceMemberListView.as_view(), name="workspace-members"),
    path(
        "workspace/members/<int:member_id>/",
        WorkspaceMemberDetailView.as_view(),
        name="workspace-member-detail",
    ),
    path(
        "workspace/invitations/",
        WorkspaceInvitationListCreateView.as_view(),
        name="workspace-invitations",
    ),
    path(
        "workspace/invitations/<int:invitation_id>/resend/",
        WorkspaceInvitationDetailView.as_view(),
        name="workspace-invitation-resend",
    ),
    path(
        "workspace/invitations/<int:invitation_id>/",
        WorkspaceInvitationDetailView.as_view(),
        name="workspace-invitation-detail",
    ),
    path(
        "workspace/invitations/<str:token>/accept/",
        WorkspaceInvitationAcceptView.as_view(),
        name="workspace-invitation-accept",
    ),
]
