# Generated by Django 6.0.6 on 2026-08-04 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('kanban', '0003_cardtransition'),
        ('process', '0004_process_work_node_and_deal_qualification'),
        ('projects', '0011_cross_project_dependencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workitemattachment',
            name='workitemattachment_exactly_one_target',
        ),
        migrations.AddField(
            model_name='workitemattachment',
            name='process_work_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='process.processworknode'),
        ),
        migrations.AddConstraint(
            model_name='workitemattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('card__isnull', True), ('process_work_node__isnull', True), ('wbs_node__isnull', False)), models.Q(('card__isnull', False), ('process_work_node__isnull', True), ('wbs_node__isnull', True)), models.Q(('card__isnull', True), ('process_work_node__isnull', False), ('wbs_node__isnull', True)), _connector='OR'), name='workitemattachment_exactly_one_target'),
        ),
    ]
